server:
  port: 8010
  servlet.context-path: /xianjinyi
spring:
  application:
    name: microservice-consumer-game


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

#microservice-provider-user2:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    config:
      microservice-provider-user:
        loggerLevel: full


logging:
  level:
    com.xianjinyi.gameConsumer.microService.MicroServiceUser: debug
